### ISSUE TITLE
[FEATURE] Single color

### ISSUE THREAD

**Issue by EKataskin** [guibranco/progressbar#26]
### What would you like to share?

Please add an option for the color of the progress bar that does not depend on the percentage.
Currently, there is no way to create a progress bar with the same color for 10% and 90%.

**Comment by guibranco** [comment]
Hi @EKataskin, 

Working on it!

**Comment by guibranco** [comment]
@EKataskin, here we are:

![Single color](https://progress-bar.xyz/10/?progress_color=ff3300) -> https://progress-bar.xyz/10/?progress_color=ff3300
![Single color](https://progress-bar.xyz/50/?progress_color=ff3300) -> https://progress-bar.xyz/50/?progress_color=ff3300
![Single color](https://progress-bar.xyz/75/?progress_color=ff3300) -> https://progress-bar.xyz/75/?progress_color=ff3300
![Single color](https://progress-bar.xyz/99/?progress_color=ff3300) -> https://progress-bar.xyz/99/?progress_color=ff3300
![Single color](https://progress-bar.xyz/100/?progress_color=ff3300) -> https://progress-bar.xyz/100/?progress_color=ff3300

**Comment by EKataskin** [comment]
Thanks, it's cool!
