### ISSUE TITLE
[FEATURE] Add various styles to the progress bars: `Plastic`

### ISSUE THREAD

**Issue by guibranco** [guibranco/progressbar#33]
Add different SVG styles for the repository and allow the style selection using the query string.

Style: `Plastic`

![plastic](https://github.com/user-attachments/assets/b03e9f42-4ee4-421c-a94a-2809b3f39f98)

**Comment by EduardoBaptista01** [comment]
Hello, trying on my first issue, can this be assigned to me?

**Comment by guibranco** [comment]
Hi @EduardoBaptista01,

Thanks for picking this up! 🙌
You have been assigned the issue.

If you have any questions or need clarification along the way, feel free to ask.

Good luck and happy coding! 😊
