### ISSUE TITLE
I do not  want to show progress number. How can I do that?

### ISSUE THREAD

**Issue by Sushnata1** [guibranco/progressbar#34]

**Comment by guibranco** [comment]
Would you like to show only the bar without text? 

That's impossible for now, but I can do it easily...

**Comment by Sushnata1** [comment]
Are you gonna add this feature now? Please tell me when I can try

**Comment by guibranco** [comment]
> Are you gonna add this feature now? Please tell me when I can try

@Sushnata1, done! You can try...

 ![Progress](https://progress-bar.xyz/28/?show_text=false) -> [https://progress-bar.xyz/28/?show_text=false](https://progress-bar.xyz/28/?show_text=false)

**Comment by Sushnata1** [comment]
Thanks bro 😊

**Comment by guibranco** [comment]
Sure, anytime!
