### ISSUE TITLE
[FEATURE] Star Rating

### ISSUE THREAD

**Issue by GoulartNogueira** [guibranco/progressbar#58]
### Description

I know the lib is for progressbar only. But I'd like to have the same concept for star ratings.

Is it too far from the scope?

I'll try to develop it myself and publish at Vercel.

Then we can decide if we merge it or just reference each other's projects.

**Comment by GoulartNogueira** [comment]
Done here:

https://github.com/goulartnogueira/starrating

If you want to merge, we could add some "mode" parameter, defaulting to "progress bar".

Anyway, I made the reference to your repo. Feel free to reference mine too.

**Comment by GoulartNogueira** [comment]
This is not a bug. Not a fix. No actions are required.

You project works fine for progress bar:  ![Progress](https://progress-bar.xyz/28/)

I just had the idea to make a similar solution to Star Rating: ![Stars](https://starrating-beta.vercel.app/2.8/)

As your project name is `Progress Bar`, I imagine a `Star Rating` is out of your scope.
That's why I just forked your repo did a similar project.

---

Now we have 2 alternatives:
1. Keep both projects in separate repositories
2. Merge them and make one single master project for Progress + Stars + Others(maybe?)

---

**Option 1:** Already done.

My project is linked to yours as an explicit fork. And I added a reference to my README:

> Inspired by guibranco/progressbar.

If you like, you could also add a reference to my project at your README.

**Option 2:** If you really like the Star Rating feature and  want to add it to your project, I suggest:
- Add a new route at your `app.py`
- Copy the code from my `app.py`.
- Update the documentation to you Readme.

```py
@app.route('/stars/<rating>/')
def star_rating(rating):
    # my code
```

If you like this idea, let me know.

**Comment by guibranco** [comment]
@GoulartNogueira added the reference to yours in the readme!

Thanks!

**Comment by GoulartNogueira** [comment]
> Hi @GoulartNogueira, I'm sorry for the bot messages. It's a third-party bot, and sometimes, it makes the issues noise.

Damn! I didn't realize I was arguing with a bot!

Hahahaha
